### ISSUE TITLE
Room numbers not displayed according to availability during booking

### ISSUE THREAD

**Issue by jesii-git57** [Tshriju-hub/HostelManagementSystem#3]
When the admin tries to book a room in the hostel management system, the available room numbers are not displayed correctly. This creates confusion and makes it difficult for users to select an available room.

**Comment by Tshriju-hub** [comment]
Update: The room numbers has been fixed according to the number of occupant that will stay in the room for example: in in No 101 delux room there will be 2 person so there can be two booking for room no 101 that's why when you fill the form for booking 2 person room no 101 will be shown twice and similar for the standard rooms with 3 persons.
